language: python
python:
  - "2.6"
  - "2.7"
cache: 
  - pip
install: 
  - "pip install -r requirements.txt -r test-requirements.txt"
script: 
  - tox -e pep8
  - "./run_tests.sh -c -V --with-selenium"
notifications:
  irc:
    - "chat.freenode.net#opendaylight-dlux"
